quarkus.mongodb.connection-string=mongodb://admin:123@localhost:27017/btgpactualdb?authSource=admin
quarkus.mongodb.database=btgpactualdb

rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=admin
rabbitmq-password=123

mp.messaging.incoming.orders.connector=smallrye-rabbitmq

mp.messaging.incoming.orders.queue.name=order-queue

mp.messaging.incoming.orders.auto-acknowledgement=false
